---
title: "Load_Estimator"
author: "TJM Fulweiler"
date: "May 24, 2017"
output: html_document
---

```{r}
#
# on River data use Richards, 1998; Rou, 2006 Beale's formula on stratified and non straified data, select the approach that generates normal data with the smallest SD possible.
# when I mention Beales I am referring to an unbiased estimator I use to generate the year mass export or "flux" of each nutrient

library(RCurl)
x <- getURL("https://raw.githubusercontent.com/tjmaguire/Load-Estimator/master/HU_data/MaumeeData_r_20170523_processed.csv")
dat <- read.csv(text = x)
dat <- dat[,-1]
rm(x)

# ensure that dat$date is an exceptable R format

dat$date = as.Date(format(as.character(dat$date,"%Y-%m-%d")), format="%Y-%m-%d")

# there can't be any missing flow data, so I am eliminating those dates
dat = dat[-which(is.na(dat[,2])==T),]

# conc data in uM/l, flow in 10^6 m3/d, fluxes in kmol/year
# find the nutrient flux for each year, each river, each nutrient

# the first col will always be date, the second col always be flow, and the other cols will rep data

# it is important to keep track of significant figures throughout, here I create a vector with each sig_fig for each nutrient

sig_fig = c(5,4,4,3,4,3,3)
samp_no = 12

# load strata files which were pre-calculated
load("C:/Users/Tim/Dropbox/Beales Method/Load-Estimator/strata_3_to_100.RData")


```

```{r}

#using the Maumee River dataset, select a random sample of size (samp_no) and generate flux estimates for each available nutrient in each available year

#Random_Sample_Fluxes <- function(dat,samp_no,sig_fig) {
  
  # use this function in the larger function, addopted from https://stackoverflow.com/questions/16357962/r-split-numeric-vector-at-position
  splitAt <- function(x, pos) unname(split(x, cumsum(seq_along(x) %in% pos)))
  library("LambertW")
  
  # conc data in uM/l, flow in 10^6 m3/d, fluxes in kmol/year
  # find the nutrient flux for each year, each river, each nutrient

  nuts = colnames(dat)[c(-1,-2)] # these are the nutrients of interest, I pull these out as colnames to select individual nutrients from the larger dataset
  nnuts = length(nuts)
  dat$year = as.numeric(format(dat[,1],"%Y"))
  results = vector("list", nnuts) # create an object to hold all our results
  names(results) = nuts
  
#  for(N in 1:nnuts) { # within each method this loop is for each nutrient
   
   # make place holders for all the data we are going to collect; method - nutrient - data 
   results[[N]] = vector("list",3)
   names(results[[N]]) = c("actual","days_in_period","est")
   
   partial = dat[which(complete.cases(dat[,nuts[N]])),] # trim data to only where that nutrient is present in the dataset
   
   results[[N]]$actual = matrix(NA,nrow =length(unique(partial$year)),ncol = 2)
   results[[N]]$actual[,1] = unique(partial$year)
   results[[N]]$days_in_period = matrix(NA,nrow =length(unique(partial$year)),ncol = 2)
   results[[N]]$days_in_period[,1] = unique(partial$year)
   results[[N]]$est = vector("list",3)
   names(results[[N]]$est) = c("Beales","inter","linear") # these are the three methods we want to examine
   
   
   for (i in 1:3){
   results[[N]]$est[[i]] = vector("list",7)
   names(results[[N]]$est[[i]]) = c("s_bias","s_sd","ns_bias","ns_sd","s_flow_strata","s_hit_miss","ns_hit_miss")
     
   results[[N]]$est[[i]]$s_bias = matrix(NA,nrow=length(unique(partial$year)),ncol=2)
   results[[N]]$est[[i]]$s_bias[,1] = unique(partial$year)
   results[[N]]$est[[i]]$s_sd = matrix(NA,nrow=length(unique(partial$year)),ncol=2)
   results[[N]]$est[[i]]$s_sd[,1] = unique(partial$year)
   results[[N]]$est[[i]]$ns_bias = matrix(NA,nrow=length(unique(partial$year)),ncol=2)
   results[[N]]$est[[i]]$ns_bias[,1] = unique(partial$year)
   results[[N]]$est[[i]]$ns_sd = matrix(NA,nrow=length(unique(partial$year)),ncol=2)
   results[[N]]$est[[i]]$ns_sd[,1] = unique(partial$year)
   results[[N]]$est[[i]]$s_flow_strata = matrix(NA,nrow =length(unique(partial$year)),ncol = floor(samp_no/3))
   results[[N]]$est[[i]]$s_flow_strata[,1] = unique(partial$year)
   results[[N]]$est[[i]]$s_hit_miss = matrix(NA,nrow =length(unique(partial$year)),ncol = 2)
   results[[N]]$est[[i]]$s_hit_miss[,1] = unique(partial$year)
   results[[N]]$est[[i]]$ns_hit_miss = matrix(NA,nrow =length(unique(partial$year)),ncol = 2)
   results[[N]]$est[[i]]$ns_hit_miss[,1] = unique(partial$year)
  } # close i

   years <- unique(as.numeric(partial$year))
   nyears = length(years)
  
#   for(y in 1:nyears){ # within method:nutrient:year
         
  year_index = which(partial$year == years[y])  # annual estimates one year at a time 
  results[[N]]$days_in_period[y,2] = length(year_index)
  results[[N]]$actual[y,2] =  signif(sum(partial[year_index,nuts[N]]*partial[year_index,2]),sig_fig[N]) # find the actual load for this nutrient in this year
  
  # within each year we need to take many random samples to define, first make temp objects to hold estimates
  
  ####
  BIGN = 10 # this is the number of random resamples
  ####
  simu = vector("list",3)
  names(simu) = c("beales","inter","linear")
  for (i in 1:3){
  simu[[i]]$s_bias = matrix(NA,nrow=BIGN,ncol=1)
  simu[[i]]$s_sd = matrix(NA,nrow=BIGN,ncol=1)
  simu[[i]]$ns_bias = matrix(NA,nrow=BIGN,ncol=1)
  simu[[i]]$ns_sd = matrix(NA,nrow=BIGN,ncol=1)
  simu[[i]]$s_flow_cuts = matrix(NA,nrow=BIGN,ncol=(floor(12/3)))
  simu[[i]]$s_hit_miss = matrix(NA,nrow=BIGN,ncol=1)
  simu[[i]]$ns_hit_miss = matrix(NA,nrow=BIGN,ncol=1)
  }
  
  partial_sample = partial[year_index,]
  
#  for (s in 1:BIGN){ # bootstrap the simulation
    
  sample_index = sample(length(year_index),samp_no,replace = F)
  partial_sample[-sample_index,nuts[N]] = NA
  flow_cuts = sort(partial_sample[sample_index,2])
  
  temp_est = vector("list",length(strata[[samp_no]]))
  temp_flow_cuts = vector("list",length(strata[[samp_no]]))
  
  for (t in 1:length(strata[[samp_no]])){ # within method:nutrient:year:strata_no
    
    temp_est[[t]] = matrix(NA,nrow=dim(as.data.frame(strata[[samp_no]][[t]]))[1],ncol = 200)
    temp_flow_cuts[[t]] = matrix(NA,nrow=dim(as.data.frame(strata[[samp_no]][[t]]))[1],ncol = (floor(12/3)))
    
    for (tt in 1:dim(as.data.frame(strata[[samp_no]][[t]]))[1]){ # within method:nutrient:year:strata_no:strata_possible
      
      dum = seq(1:samp_no)
      if(t==1){
      strata_index = list(dum)
      } else {
      strata_index = splitAt(dum,(as.vector(strata[[samp_no]][[t]]$strata[tt,])+1))
      }
      
      temp_data = vector("list",length(strata_index))
      

      for (ttt in 1:length(strata_index)){ # build temp data based on specific strata possibility
      
   if(ttt == 1){
     ttt_index = which(partial_sample[,2] <= flow_cuts[max(strata_index[[ttt]])])
     temp_flow_cuts[[t]][tt,ttt] = flow_cuts[max(strata_index[[ttt]])]
     } else if(ttt == length(strata_index)){
       ttt_index = which(partial_sample[,2] >=     flow_cuts[min(strata_index[[ttt]])])
       temp_flow_cuts[[t]][tt,ttt] = flow_cuts[min(strata_index[[ttt]])]
       } else {
       ttt_index = intersect(which(partial_sample[,2] <= flow_cuts[max(strata_index[[ttt]])]),which(partial_sample[,2] >= flow_cuts[min(strata_index[[ttt]])]))
       temp_flow_cuts[[t]][tt,ttt] = flow_cuts[max(strata_index[[ttt]])]
     }

  temp_data[[ttt]] = partial_sample[ttt_index,]
  
      } # close ttt
  

  
# temp_est[[t]][tt,]  this is where the final estimates should go per strata
  temp_temp_est =   vector("list",length(strata_index)) # this is where the temp data will sit
  

   for(tttt in 1:length(strata_index)){ # divide data as per strata possibility
      temp_temp_est[[tttt]] = matrix(NA,nrow=1,ncol=200)

     for(ttttt in 1:200){ # boot strap data within each strata possibility and sum
      boot_index = sample(length(strata_index[[tttt]]),length(strata_index[[tttt]]),replace = T)
      boot_sample = which(is.na(temp_data[[tttt]][,nuts[N]])==F)[boot_index]
    
        temp_data[[tttt]]$flux = temp_data[[tttt]][,2]*temp_data[[tttt]][,nuts[N]]
        
        ux=mean(temp_data[[tttt]][,"flow"])
        my=mean(temp_data[[tttt]][,"flux"],na.rm = T)
        mx=mean(temp_data[[tttt]][boot_sample,"flow"])
        n=length(boot_sample)
        bigN=length(temp_data[[tttt]][,"flow"])
        xi=temp_data[[tttt]][boot_sample,"flow"]
        yi=temp_data[[tttt]][boot_sample,"flux"]
        Sxy=cov(xi,yi)
        Sxx=var(xi)
        
        temp_temp_est[[tttt]][,ttttt] = signif((ux*(my/mx)*((1+(1/n)*(Sxy/(mx*my)))/(1+(1/n)*(Sxx/mx^2))))*bigN,sig_fig[N])
       
     } # close ttttt
   } # close tttt    
        
  # temp_temp_est now holds the bootstrapped strata and needs to be summed
  
temp_est[[t]][tt,] = colSums(matrix(unlist(temp_temp_est), ncol = 200, byrow = TRUE))
} # close tt
} # close t

all_strata_beales = do.call(rbind, sapply(temp_est, unlist))
# I want to pick the flow stratification (or non) set that generates estimates that are normal, 
        # then compare across these and take the one with the smallest sd
        # the selection object has one col of p-values and one col of sd's

# create empty holder for (1) is the est generated by each strata normal (2) what is the sd
holder= matrix(NA,nrow=length(all_strata_beales[,1]),ncol = 3)
holder[,1] = 0 # zero will indicate not normal

for(i in 1:length(all_strata_beales[,1])){
beta.true <- c(location = mean(all_strata_beales[i,]), scale = sd(all_strata_beales[i,]), df = samp_no)
holder[i,2] = sd(all_strata_beales[i,])
holder[i,3] = ks.test.t(all_strata_beales[i,], beta.true)$p.value
if (holder[i,3] <= 0.05){
holder[i,1] = 1
}}

# if any are normal, select the one with the smallest SD, if none are select the one that is "closest" to being normal via smallest p-value in ks.test.t
if(any(holder[,1]==1)){
norm_index  = which(holder[,1]==1)
selection = which(holder[norm_index,2] == min(holder[norm_index,2]))
} else {
selection = which(holder[,3] == min(holder[,3]))
}

simu$beales$s_bias[s,] =  abs(mean(all_strata_beales[selection,])-results$ss$actual[y,2])
simu$beales$s_sd[s,] = sd(all_strata_beales[selection,])
simu$beales$ns_bias[s,] = abs(mean(all_strata_beales[1,])-results$ss$actual[y,2])
simu$beales$ns_sd[s,] = sd(all_strata_beales[1,])

all_strata_cuts = do.call(rbind, sapply(temp_flow_cuts, unlist))

simu$beales$s_flow_cuts = all_strata_cuts[selection,]

if(quantile(all_strata_beales[selection,],c(0.025,0.975))[1] <= mean(all_strata_beales[selection,]) &
quantile(all_strata_beales[selection,],c(0.025,0.975))[2] >= mean(all_strata_beales[selection,])){
simu$beales$s_hit_miss[s,] = 1
} else {
simu$beales$s_hit_miss[s,] = 0
}



```
